name: Deploy Staging Environment to Fly
on:
  push:
    branches:
      - staging
env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
jobs:
  deploy-backend:
    name: Deploy backend app
    environment: staging
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: debug
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          echo "TEST=${DB_HOST}:${DB_PASSWORD} and something else..."
